config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/secure', to: 'secure#index', as: :secure
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  devise :trackable, :cas_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/secure_controller.rb
class SecureController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secure_helper.rb
module SecureHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<p><%= link_to('Go to secure page', secure_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <p>
        <strong><%= current_user.username %></strong>
        <%= link_to('Sign out', destroy_user_session_path, method: :delete) %>
      </p>
    <% end %>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/secure/index.html.erb
<h1>This page is secure</h1>